# Generated by Django 5.0.4 on 2024-04-28 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vector_injest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DatabaseUnit',
            new_name='DatasetUnit',
        ),
        migrations.RenameField(
            model_name='datasetunit',
            old_name='database_unit_description',
            new_name='dataset_unit_description',
        ),
        migrations.RenameField(
            model_name='datasetunit',
            old_name='database_unit_name',
            new_name='dataset_unit_name',
        ),
    ]
