# Generated by Django 5.0.4 on 2024-04-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_short_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
