# Generated by Django 5.0.4 on 2024-04-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_unit_name', models.CharField(max_length=300)),
                ('database_unit_description', models.TextField()),
                ('date_added', models.DateTimeField(verbose_name='date added')),
                ('content_path', models.CharField(max_length=500)),
                ('directory_structure', models.TextField()),
            ],
        ),
    ]
